export const GET_SEARCHHIS = 'GET_SEARCHHIS'
export const SET_SEARCHHIS = 'SET_SEARCHHIS'
export const CLEAR_SEARCHHIS = 'CLEAR_SEARCHHIS'
export const HAS_HISTORY = 'HAS_HISTORY'
export const SET_CURRENTSEARCH = 'SET_CURRENTSEARCH'
export const SET_CURRENTCITY = 'SET_CURRENTCITY'
//操作确认订单
export const SET_CONFIRMORDER = 'SET_CONFIRMORDER'
export const SET_BGSHOWHIDE = 'SET_BGSHOWHIDE'

// 订单列表
export const SET_ORDERLIST = 'SET_ORDERLIST'
export const SET_ORDERMANAGE = 'SET_ORDERMANAGE'
